# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: MySQL
    orgId: 1

   httpMode: GET

- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://localhost:9090
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    httpMethod: GET
  # <string> json object of data that will be encrypted.
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

- name: MySQL
  # <string, required> datasource type. Required
  type: mysql
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: bookstore-mysql-db:3306
  # <string> database user, if used
  user: bookstoreDBA
  secureJsonData:
    # <string> database password, if used
    password: PaSSworD
  # <string> json object of data that will be encrypted.
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true