CREATE TABLE farm_leases (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    farmerName VARCHAR(255) NOT NULL,
    farmAddress VARCHAR(255) NOT NULL,
    crop VARCHAR(255) NOT NULL,
    acres INTEGER NOT NULL,
    pricePerAcre DOUBLE NOT NULL
);